<a href="https://colab.research.google.com/github/belokonr/Breast-Cancer-Study/blob/main/notebooks/01_DataProcessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [4]:
#load data
RF_FILE_1 = 'bcsc_risk_factors_summarized1_092020.csv'
RF_FILE_2 = 'bcsc_risk_factors_summarized2_092020.csv'
RF_FILE_3 = 'bcsc_risk_factors_summarized3_092020.csv'
MAM_FILE = 'BCSC_Mammography_Screening_Performance_Dataset.csv'

In [5]:
#clean data
rf_1_df = pd.read_csv(RF_FILE_1)
rf_2_df = pd.read_csv(RF_FILE_2)
rf_3_df = pd.read_csv(RF_FILE_3)
mam_db = pd.read_csv(MAM_FILE)

In [14]:
#for risk factor datasets, combine all three csv's using concatenate
rf_list = []
rf_list.append(rf_1_df)
rf_list.append(rf_2_df)
rf_list.append(rf_3_df)
rf_db = pd.concat(rf_list, ignore_index=True)

In [15]:
rf_db.head()

,year,age_group_5_years,race_eth,first_degree_hx,age_menarche,age_first_birth,BIRADS_breast_density,current_hrt,menopaus,bmi_group,biophx,breast_cancer_history,count
0,2013,7,1,0,9,3,1,1,2,3,0,0,7
1,2013,7,1,0,9,3,1,1,2,3,1,0,3
2,2013,7,1,0,9,3,1,1,2,4,0,0,6
3,2013,7,1,0,9,3,1,1,2,4,1,0,1
4,2013,7,1,0,9,3,1,1,2,4,1,1,1

In [17]:
# remove all risk factor variables we aren't interested in
#rf_df = rf_db[['age_group_5_years', 'BIRADS_breast_density', 'current_hrt', 'bmi_group']]

cols_to_check = rf_db.columns.difference(['age_group_5_years', 'count'])

mask = (rf_db[cols_to_check] != 9).all(axis=1)

rf_df = rf_db[mask]

# remove all instances of unknown data and NaN's
#rf_df = rf_df.dropna()
#rf_df = rf_df[rf_df['BIRADS_breast_density'] != 9]
#rf_df = rf_df[rf_df['current_hrt'] != 9]
#rf_df = rf_df[rf_df['bmi_group'] != 9]

# transform age variable to store as 18-85 instead of 1-13
# the values in our case will be the lower limits of the age range for each group
rf_df['age_group_5_years'] = (rf_df['age_group_5_years'] * 5) + 20
# replace 25 with 18 as age group 1 is 18-29, unlike all others which go by 5 years
rf_df['age_group_5_years'].replace(25, 18, inplace=True)

# transform bmi variable to store as 10-35 instead of 1-4
# the values in our case will be the lower limits of the bmi range for each group
rf_df['bmi_group'] = (rf_df['bmi_group'] * 5) + 15
# replace 20 with 10 as bmi group 1 is 10-24.99, unlike all others which go by 5 units
rf_df['bmi_group'].replace(20, 10, inplace=True)

# name columns recognizeably
#rf_df.columns = ['Age', 'Breast Density', 'HRT', 'BMI']

rf_df.head()

/tmp/ipykernel_282/1840478816.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rf_df['age_group_5_years'] = (rf_df['age_group_5_years'] * 5) + 20
/tmp/ipykernel_282/1840478816.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  rf_df['age_group_5_years'].replace(25, 18, inplace=True)
/tmp/ipykernel_282/1840478816.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rf_df['age_group_5_years'].replace(25, 18, inplace=True)
/tmp/ipykernel_282/1840478816.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rf_df['bmi_group'] = (rf_df['bmi_group'] * 5) + 15
/tmp/ipykernel_282/1840478816.py:26: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  rf_df['bmi_group'].replace(20, 10, inplace=True)
/tmp/ipykernel_282/1840478816.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rf_df['bmi_group'].replace(20, 10, inplace=True)

,year,age_group_5_years,race_eth,first_degree_hx,age_menarche,age_first_birth,BIRADS_breast_density,current_hrt,menopaus,bmi_group,biophx,breast_cancer_history,count
1411,2013,55,1,1,0,0,1,0,2,30,0,0,2
1412,2013,55,1,1,0,0,1,0,2,35,1,0,1
1413,2013,55,1,1,0,0,1,0,3,25,1,0,1
1414,2013,55,1,1,0,0,1,0,3,35,0,0,1
1415,2013,55,1,1,0,0,2,0,1,30,0,0,1

In [18]:
mam_db.head()

,agegrp,density_c,examyear_cat,riskBCSC_v2_5y_cat,resinit_c,resfnl_c,resfnl_c3,cancscrfu1yr_c,dcisscrfu1yr_c,invscrfu1yr_c,stage_advanced,count
0,40-49,unknown,2005-2008,unknown,0: Negative,0: Negative,0: Negative,0: No,0: No,0: No,0: No,19320
1,40-49,unknown,2009-2010,unknown,0: Negative,0: Negative,0: Negative,0: No,0: No,0: No,0: No,10035
2,40-49,unknown,2011-2012,unknown,0: Negative,0: Negative,0: Negative,0: No,0: No,0: No,0: No,12778
3,40-49,unknown,2013-2014,unknown,0: Negative,0: Negative,0: Negative,0: No,0: No,0: No,0: No,5708
4,40-49,unknown,2015-2017,unknown,0: Negative,0: Negative,0: Negative,0: No,0: No,0: No,0: No,663